### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by limazix** [yuri-lisboa/deep-learning-math-skills#1]
## Tools

1. [Python](https://www.python.org/) (***v3.5+***)
2. [Poetry](https://python-poetry.org/)
2. [Jupyter](https://jupyter.org/)
3. [Matplotlib](https://matplotlib.org/)
4. [Seaborn](https://seaborn.pydata.org/)
5. [NumPy](https://numpy.org/)
6. [Pandas](https://pandas.pydata.org/)

## Tasks

- [x] Install Poetry globally using Homebrew on macOS environments.
- [x] Create the project structure using Poetry
- [ ] Create a README file with the project's description and its dependencies
- [x] Install Jupyter and make it run
- [x] Create a dummy notebook for testing purpose
- [x] Install all other libraries using Poetry
- [x] Import all libraries from the dummy notebook
- [ ] Update the README file describing how to use the repository
